services:
    nginx:
        image: nginx:latest
        container_name: nginx-reverse-proxy
        ports:
          - "80:80"
          - "443:443"
          - "5432:5432"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          - ./certs:/etc/nginx/certs:ro
          - ./html:/usr/share/nginx/html:ro
        restart: unless-stopped
